src/containers/ClassifierTester.jsx
src/ducks/reducer.js
src/ducks/subject.js
src/lib/get-subject-location.js
src/styles/components/tester-page.styl

This is based pretty closely to the project retrieval with the addition of the queue. There might be some intrinsic changes that need to be made, as this is the second time I've used Redux, so I'm open to suggestions.
Working through this, there should also be a subject location reader helper method, similar to what exists in PFE. I might push this up in another commit, but if you review this before that commit, feel free to merge and I'll add the addition in another PR.

Retrieve Subject and Queue

---

src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/subject-viewer.js

* This PR fixes #23 
* With this PR, calling the 'Reset Image' functionality (either on Subject image load, or when clicking the 'Reset Image' button on the Classifier controls) also calls the 'best fit Subject image to viewer' functionality.
* As a result of these changes, the Image Size and Subject Viewer Size data is now stored within the Redux store.
Ready for review

'Reset Image' functionality also does auto-best-fit of Image size

---

package.json
webpack.production.config.js

* In this PR, we're adding the ability for us to publish our website to https://www.antislaverymanuscripts.org/
* To do so, run `npm run deploy-production` on the command line.
* Of course, this only applies to Zooniverse developers with access to the production servers.
* Note that due production-staging shenanigans, if you view https://www.antislaverymanuscripts.org/ new, you'll see some Subjects from Notes from Nature (butterflies!) instead of something more text/transcription-based. This is because that, for testing, the project/subject queue/etc IDs are all hard-coded and the NfN project is what you see on production; to view the 'proper' testing images, add the `staging` switch: https://www.antislaverymanuscripts.org/?env=staging
Ready for review! Don't forget to run `npm install` …

Add "Deploy to Production" command line action

---

src/containers/ClassifierContainer.jsx

* Minor bugfix
* Currently, when we open the Classifier Page, the test popup... pops up.
* This makes development a bit of annoyance, what with our frequent page reloads.
* As such, I've hidden the Test Popup so it only appears when you click on the "Test Popup" button on the Classifier page. (See the right-hand tools)
* Obviously, once we start using the popup mechanics for proper messaging, we can remove the example used in the Classifier page.
I'm merging this straight away so dev work won't be hindered by the unexpected popups. Tagging @wgranger as a FYI.

Bugfix: Hide 'Test Popup' when loading Classifier Page

---

src/containers/SubjectViewer.jsx

Closes #33 
This PR simply remove the `onWheel` event attached to the subject viewer based on suggestions that the wheel zoom was a bit too sensitive. If we need to reinstate the functionality, we can refer back to this PR.

Remove onWheel Zoom Event

---

src/containers/Navigator.jsx

* The PR was originally an attempt to fix why the Subject images aren't fitting properly into Subject Viewer.
_Look at that Subject image, it's so tiny. It should fit neatly into the Subject Viewer's viewport._
* But then I realised... the Subject Images themselves were wonky, with plenty of empty space to the left and right. (e.g. https://panoptes-uploads.zooniverse.org/staging/subject_location/f9e4c84c-169c-44a2-b0bd-153602bd366f.png )
_What in the..._
* Instead, the only substantial change in this PR is the fix of Navigator's `Navigator.props.imageSize` PropTypes, which wasn't using the PropType.shape that it should have.
Ready for review. The question of wide Subject Images is probably something separate to explore...

Fix Image size/Resizing

---

src/components/FilmstripViewer.jsx

Closes #48 
This PR uses thumbnail versions of an image to cut back on load time of the FIlmstrip Viewer when opening the classifier.

Use Thumbnail Sizing

---

package.json
src/components/App.jsx
src/components/Home.jsx
src/styles/components/app-header.styl
src/styles/components/home-page.styl
src/styles/components/temp-placeholders.styl
src/styles/main.styl
webpack.config.js
webpack.production.config.js

In this PR, the footer is added from the newly updated Zooniverse-react-components repo. As the repo uses Grommet, several styling changes affected the view of the app, which is reflected in the CSS changes also made in this PR.

Add Footer from Shared Components

---

src/components/ZoomTools.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/styles/components/subject-viewer.styl
src/styles/components/zoom-tools.styl

Fixes #52 Fixes #22 
Per design suggestions, this PR moves zoom and pan functionality to the subject viewer. The cursor has also changed to a move icon when navigating.

Move Zoom Tools to Subject Viewer

---

src/styles/components/subject-viewer.styl

This is a fix on the subject viewer overflow. Currently, the annotation pane is hidden behind any content besides the subject viewer container.

Fix Subject Viewer Overflow

---

src/components/AnnotationsPane.jsx

* Fixes #72 
* Classifications page on localhost:3000/classify would have issues rendering some Subjects (presumably, those without previous markings)
* Turns out this was due to `AnnotationsPane.renderPreviousAnnotations` not checking the existence of `currentAnnotations.clusters_text` before trying to `.map()` it.
* Fix is a simple check before execution.
* @wgranger it occurs to me that the reason I didn't catch this earlier was because the `currentAnnotations.clusters_text` was _always_ provided... which hints that Caesar is likely now _live_ with the new text aggregation updates, wooo ( https://github.com/zooniverse/aggregation-for-caesar/pull/34 )
Ready for review just in case there's anything else obvious I missed. Otherwise, since this is minor, I'll merge within 24 hours.

Fix 72: AnnotationsPane now checks for currentAnnotations.clusters_text

---

src/components/SelectedAnnotation.jsx
src/ducks/annotations.js
src/ducks/previousAnnotations.js

- This PR adds the ability to delete an active (Selected) Annotation.
- The Delete button appears on the Text Input dialog that appears when a Selected Annotation is, well, selected. (Either upon clicking an existing Annotation that the user created, or after finishing the process of creating a new one. The Delete button does NOT appear on Aggregated (other people's) Annotations.
WIP. When those checkboxes above are all ticked out, I'll submit this for a full review.

Feature: Delete Selected Annotation

---

src/components/AnnotationsPane.jsx

- This PR reorganises the order of the annotations so...
- New (currently in progress) Annotations appear above...
- User's (completed) Annottations, which appear above...
- Previous (collaborative) Annotations.
- This is a _visual workaround_ that essentually fixes #97 .
- The core of issue #97 is that when you Agree to a Previous Annotation on page 1, then switch to page 2 then back to page 1, the Previous Annotation now appears _overlaid on top of_ your Agreement Annotation.
- This change essentially obscures the Previous Annotation behind the Agreement Annotation instead of simply not rendering the former.
- Note: if this is the 'proper' solution going forward, it may also make the ("Reenable Previous Annotation"](https://github.com/zooniverse/liberating-the-liberator/pull/92/commits/8 …

Reorder Annotations - User Annotations now above Previous Annotations

---

src/components/AboutTheCollection.jsx
src/components/AboutTheProject.jsx
src/components/Home.jsx
src/containers/ClassifierContainer.jsx
src/lib/letter-groups.js
src/lib/project-members.js
src/styles/components/about-project.styl
src/styles/components/app-layout.styl
src/styles/components/classifier-page.styl
src/styles/components/home-page.styl

Fixes #95 
This fixes some design suggestions based on a review of the landing and about the project page. Some content text is also changed in the about sections.
This PR also fixes the issue above, which was the result of `background-size: cover` when a popup was present.
Note: Footer suggestions should probably be done on the ZRC repo?

Adjust Fonts and Spacing Post-Design Review

---

src/ducks/classifications.js

Issue: when a user Submits a Classification (i.e. clicks Done), the next time they do so, they encounter an error.
Analysis:
- the createClassification() initialiser isn't properly called on all instances of a new Subject being loaded.
- See ClassifierContainer:
```
componentWillReceiveProps(nextProps) {
if (nextProps.currentSubject && nextProps.workflow && !this.props.classification) {
this.props.dispatch(createClassification());
}
}
```
Solution:
- We force a createClassfication() call within the Submit Classification action itself.
- This may cause double work (since the componentWillReceiveProps seems rather random on when it creates a Classification) but it's a relatively safe method.
- While this PR fixes the Submit a Classification bug, it may expose a problem with the next set of …

Fix Submit Classification bug

---

src/components/SocialSection.jsx

Closes #108 
This was a relatively easy fix since all of the resources needed are already attached to the project resource. Although pusher is used in PFE to update the classification count, it only seems secondary to what is [already included in the project resource](https://github.com/zooniverse/Panoptes-Front-End/blob/0f3b9c02c4b8e031bc5e4fa8d3674ea170c9281f/app/pages/project/home/metadata.jsx#L27). 
Because of this, I don't think Pusher is necessary. However, if we experience discrepancies after launch, then we can update this code.

Add Project Stats from Project Resource

---

src/components/SVGImage.jsx

Issue: In Safari (OSX+Safari11) the `<image>` inside the `<svg>` doesn't show properly.
Analysis:
As it turns out, for Safari, the minimum needed for an inline SVG with an image is...
```
<svg>
<image
width="..." height="..."  //Required.
xlink:href="image.png"   //Required. 'xlinkHref' in JSX. Previously, we were using 'href'.
/>
</svg>
```
Solution: In `SVGImage`, we replace `href` with `xlinkHref` (which translates to `xlink:href` in the actual HTML.)
Here's an example of some minimal SVG code that works in OSX+Chrome/FF/Safari and Win7+IE11 for future testing.
```
<!DOCTYPE html>
<html>
<head>
<title>Inline SVG Image Test</title>
</head>
<body>
<h1>Inline SVG Image Test</h1>  
<svg
width="400"
height="250"
style="border: 1px solid #333"
>
<circle r="125" cx="200" cy="125" fill="#39c" …
```

Fix Safari's SVG image bug

---

src/components/App.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/classifications.js
src/ducks/subject.js

- This PR handles two major issues.
- First, the **fetching Subject-Classification lifecycle** has been refactored.
- Instead of `createClassification()`  triggering inside `ClassifierContainer` as it waits for a new Subject to come in...
- ... `createClassification()` is now triggered directly after a Subject is successfully fetched within its Duck. i.e., we're removing the 'React component monitoring for changes' bit.
- Second, this PR fixes an issue where you can't get the third Subject from your queue.
> Issue: after submitting the Classification for the second Subject in your queue, you can't load any more Subjects - the system crashes. 
> Analysis: In `fetchSubject()`, there's an if-else fork that either A. fetches a new Subject Queue and the latest Subject on that queue, or B. …

Streamline fetch lifecycle and fix fetching Subject from queue

---

src/ducks/subject.js

- There are two issues with the Panoptes `/queued` request for Subjects. (See Issue #125)
- One: logged in vs non-logged in get very different queues.
- Two: when we set a new Subject Set id, the existing queue isn't cleared, so the new Subject Set isn't actually requested.
- This PR fixes Issue TWO only, by resetting the internal queue whenever a new Subject ID is selected.
TL;DR this is difficult to test, but it looks like it works to me.
Anyway. Testing this will be odd given that ASM has about 5 Subject Queues with only 1 Subject each, and given Issue One above. This is the only way I can tell that it works, on localhost, while not logged in: _(It always looks fine while logged in due to the combination of Issue 1 and the small Subject Sets.)_
1. As a non-logged in user, I always see …

Fix Subject queue not making sense

---

src/components/SelectedAnnotation.jsx

This PR contains basic functionality for text modifiers. I borrow code based on suggestions by @simensta. Everything appears to be working; however I still have a couple questions.
1) Basic UI - should we find a way to display this information when it comes back to a user from a previous annotation? ex. Would "This is [insertion]a test[/insertion]" rattle a user?
2) Should we write another bit of code to pad text correctly or trust a user to follow directions? ex. "Here is some [insertion] text I am [/insertion] writing" would throw off the reducer's word count.
Closes #65

Functioning Text Modifiers

---

src/config.js

This PR doesn't necessarily "fix-auth" on production (as the branch is titled). That work is done with getting the site whitelisted. However, this PR changes the app id on staging to a unique not shared by another app.

Change Staging App ID

---

src/config.js

- This PR changes the ID for the production workflow.
- Following the conversation on Slack, the new production workflow (5329) was created to much better copy the structure set up by the staging workflow (3017).
- The `grouped: true` attribute of the workflow had to be set separately, via the zooAPI dev tool.
Minor change; I'll take responsibility for merging this.

Change workflow ID for production

---

src/containers/ClassifierContainer.jsx

- This PR temporarily hides (i.e. _/*comments out*/_ ) all mention of the Cribsheet from the Classifier page.
- The Cribsheet isn't ready yet, so there's no reason to confuse people with mention of it right now.
Minor update, and I'm taking responsibility for merging.

Hide Cribsheet button & instructions in Classifier page

---

src/components/AnnotationsPane.jsx
src/components/PendingAnnotation.jsx
src/components/SelectedAnnotation.jsx
src/containers/SubjectViewer.jsx
src/styles/components/selected-annotation.styl
src/styles/global/app-theme.styl

This PR contains three main logic checks:
1) Disable the "done" button on the `SelectedAnnotation` pane until the correct amount of words have been typed.
2) Disallow a user to create an annotation point unless the points are in a line.
3) Pulsate the most recent annotation point as a signifier that it can be clicked to end an annotation.
*Note: The second item was done with a separate component to keep the entire `AnnotationPane` from updating when `setState` was called with a mouse move. Also, I'm open to ideas on the third item as I know SVG animations are not supported by all browsers, and this was the first solution I arrived upon.
Closes #75

Annotation Logic Checks

---

package.json

- @wgranger recently changed the repo name from `liberating-the-liberator` to `anti-slavery-manuscripts` to better reflect the current project identity.
- This PR is a minor informational update to the project's package.json, which had hitherto been referring to the liberating-the-liberator repo.
Minor update, I'm taking responsibility for this merge.

Update package.json's URLs

---

src/ducks/splits.js

Since we are beginning seven-ten testing on production, we needed to update the split duck to find the correct slug depending on the environment.

Use Config to Determine Split Slug

---

src/config.js
src/ducks/previousAnnotations.js

This PR adds the correct Caesar production host depending on environment. Error handling and a status state has also been added while fetching previous annotations.
Note: I'm still getting a 404 with new subjects that have no previous annotations attached. Still to be confirmed that is the expected response from the backend.

User Caesar Production Host

---

src/components/AnnotationsPane.jsx
src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx
src/ducks/subject-viewer.js
src/styles/components/classifier-page.styl

This PR addresses two issues:
1) Show gray consensus lines for both collaborative *and* individual splits. Closes #146 
2) Adjust the toggle state for "toggle prev. marks." Now, the user may toggle between seeing all/previous annotations, seeing only user annotations, seeing only current annotation. *Note:* a check was made to only toggle between all marks and no marks if no previous annotations are present.

Show Gray Lines on Individual Split

---

src/components/ProjectHeader.jsx
src/components/SubmitClassificationForm.jsx
src/components/Timeline.jsx
src/containers/ClassifierContainer.jsx
src/styles/components/zoom-tools.styl

There were a couple issues with focus that arose from internal testing. The major issue with focus is finding a way for the subject viewer to interact with the keyboard, which will require more attention.
For now, this PR accomplishes three items:
1) Remove double focus or project header items ("About" and "Talk")
2) Add focus styling to zoom buttons
3) Add focus and interactivity to SVG items on the timeline
4) Remove `href="#"` from buttons

Add Accessibility to Focus Items

---

src/components/SelectedAnnotation.jsx
src/styles/components/selected-annotation.styl

Currently, the sole commit in this PR handles the restyling mentioned in #149. However, I'm still unclear about the following:
- Are we allowing users to submit a classification if the word count doesn't match the number of dots (using a disclaimer)?
Closes #149

Restyle Word Count Indicator

---

src/components/SelectedAnnotation.jsx

- With this PR, when a user creates a new Annotation and then proceeds to Cancel it (or clicks on the X to close the window) on the Transcription popup, that new Annotation is _deleted._
- For our purposes, a 'new Annotation' can be implied when the selected annotation has zero transcribed text.
- This prevents users from submitting Annotations with no text, simply by cancelling out of a newly created Annotation (which has no text).
- Clicking Cancel or close on an existing Annotation simply reverts the Annotation to its previous state, (i.e. before the Transcription popup appeared,) as normal.
Ready for review, @wgranger

Cancelling a new Annotation now deletes it

---

src/components/Home.jsx
src/config.js
src/ducks/subject.js
src/styles/components/home-page.styl

This is necessary for beta launch. Instead of giving users the option to choose which subject set they draw from, the beta subject set will be the only one used. This should be removed eventually for full launch.
Currently RFC because there might be the same issue with the `subject_set_id` query failing to pull subjects from the correct set, but I'd like another set of eyes on the code to confirm.

[RFC] Only Use Beta Subject Sets

---

src/containers/SubjectViewer.jsx
src/ducks/classifications.js
src/ducks/previousAnnotations.js
src/ducks/subject.js

The original issue that this PR attempts to fix is phrased this way: _When a user makes Annotations on Subject A, then navigates away from the Classifier page, then returns, they will see Subject B loading, but with Subject A's Annotations._
This was due to the fact that the Subject fetching lifecycle was somewhat broken. This PR improves the lifecycle by _ensuring_ that when a new Subject is successfully fetch, all items that _should follow that event in the lifecycle_ will accordingly be reset into a blank slate.
i.e., when a new Subject is fetched successfully,
- reset Annotations
- reset Previous Annotations
- create a new, empty Classification
- reset the Subject Viewer so it's pointing back to page 1 of the Subject letter.
- Are Previous Annotations still displaying properly for a …

Successfully fetching Subjects now properly resets Annotations, Previous Annotations, and Classifications

---

src/components/App.jsx

Good this was caught in time for beta. There was an important line that was slightly off where the GA client wouldn't remember a variant if it never changed from individual.

Fix .remember GA Call

---

src/components/App.jsx
src/components/Home.jsx
src/config.js
src/containers/ClassifierContainer.jsx
src/ducks/classifications.js
src/ducks/login.js
src/ducks/project.js
src/ducks/splits.js
src/ducks/subject.js
src/ducks/workflow.js
src/styles/components/classifier-page.styl
src/styles/components/home-page.styl

This PR opens a Gold Standard Mode which will have access to a separate workflow to record gold standard annotations. I initially set out to refactor the code a bit, but I feel like this is a case where a good bit of code is needed to accomplish a simple task (fetching roles, running conditionals, rendering based on these results).
Currently, only an owner and expert can enter gold standard mode via the home screen. I came across two minor issues with this branch, but I'm not sure it's worth a fix since (as to my knowledge) we only have one person currently who will be annotating under this mode.
1) If a user logs out while in gold standard mode, the mode will not be reset.
2) There is a reloading and jumping of the home page when gold standard mode is toggled (probably because a new …

Open Gold Standard Mode

---

src/components/Dialog.jsx

This was a relatively easy fix. The dialog modal wasn't placing right on IE because the browser can't recognize `window.scrollY`. Alternatively, I used `window.pageYOffset`.
I believe this is the final fix needed to close #18 
Closes #18

Fix Modal Placement on IE

---

src/containers/ClassifierContainer.jsx
src/styles/components/classifier-page.styl

This had somewhat been cleared up by switching the subject viewer status away from annotate when a selected annotation existed, but this change disables the button from being pressed, thus closing an issue.
Closes #59

Disable background annotate

---

src/components/ProjectHeader.jsx
src/styles/components/project-header.styl

This PR adds a link for feedback forms on the project header in preparation for beta launch. A user will be directed to an individual or collaborative form depending on which variant group is used.

Reveal Feedback Forms

---

src/components/SocialSection.jsx

This PR fixes the `@BPLBostom` typo on the home page's Social Section ("In The News")
Minor fix, merging.

Typo fix - @BPLBostom

---

src/components/SocialSection.jsx

Whoops. Just a small bug that got into production and wasn't visible until stats came in.

Round Project Completeness Stat

---

package.json
src/components/App.jsx
src/components/ClassificationPrompt.jsx
src/components/Dialog.jsx
src/components/Home.jsx
src/components/SaveSuccess.jsx
src/containers/ClassifierContainer.jsx
src/ducks/annotations.js
src/ducks/classifications.js
src/ducks/dialog.js
src/ducks/subject.js
src/styles/components/about-collection.styl
src/styles/components/about-project.styl
src/styles/components/app-layout.styl
src/styles/components/classification-prompt.styl
src/styles/components/classifier-page.styl
src/styles/components/submit-classification-form.styl

This PR is the second attempt at adding the feature which allows logged-in users to _manually_ save all the Annotations they've done, and resume Classifying at a later date.
This feature was originally added in PR #164 but reverted in PR #180 . The reason:
- When a user attempts to Submit a Classification, they'd receive _Error: Could not submit Classification_ with the following console error:
- `PUT https://panoptes-staging.zooniverse.org/api/classifications/89036 422 (Unprocessable Entity)`
- `Submit classification: Error -  Error: {"schema"=>"did not contain a required property of 'annotations'"}`
- Request payload is:
```
{  
"http_cache":true,
"classifications":{  
"completed":true,
"metadata":{  
"session":"6365883a0a1763274133432875d9320dcdf51fe0fac064e1c88efa50b4b058e9", …
```

Save Classifications for Later - Mk2

---

package.json
src/components/Header.jsx

Zooniverse-React-Components updated the header component, so this PR makes those changes to the package.json
Notable changes include the addition of the `isAdmin` prop to the ZooHeader as well as the ability to toggle between mobile and desktop views.
There were also a few items being imported into the ASM header component that were unnecessary.

Update to New Header and Add Admin Prop

---

src/components/Dialog.jsx
src/components/FieldGuide.jsx
src/components/ShowMetadata.jsx
src/containers/ClassifierContainer.jsx
src/ducks/dialog.js
src/styles/components/collections-manager.styl
src/styles/components/field-guide.styl
src/styles/components/popup.styl
src/styles/components/show-metadata.styl
src/styles/components/submit-classification-form.styl

Not all headers are given a dialog (such as simple popups). However, the main use case here was the give the metadata popup a distinct header that stood out and stayed at the top when scrolling.
Additional line changes were made to keep the linter uniform.

Add Header to Dialogs

---

src/components/AnnotationsPane.jsx
src/containers/SubjectViewer.jsx
src/styles/components/subject-viewer.styl

This branch is working, but there are a couple questions lingering during the review:
Currently, a user will not have a mouse down event over a previous annotation when in navigating or annotating mode. If this appears to throw off the user, I can pass those functions into a child prop to replicate their functionality. Just something to take note of during review.
Also made some line changes to appease the linter.
Closes #176

Hover Message on Gray Line

---

src/components/AnnotationsPane.jsx
src/components/Dialog.jsx
src/components/Popup.jsx

This PR makes some minor improvements to how we code Events.
- Retired Annotation Lines no longer eat mouse events, meaning we can now Pan (and Annotate)
actions work when the mouse is over these greyed-out lines. (see PR #185 )
- Dialog and Popup both had their own versions of stopEvent(), which is actually a shared function available by the lib/Utility object. This PR standardises the use of stopEvent() in both components.
Ready for review.

Retired Annotation Lines don't eat mouse events, plus stopEvent improvements

---

src/containers/SubjectViewer.jsx
src/ducks/previousAnnotations.js
src/ducks/subject.js

This PR fixes the bugs that currently exist with two ducks using the config file for the default individual workflow. Instead of discerning which variant a user is placed (individual/collaborative), the config always defaults to the individual workflow.
I'd like to figure out why Caesar is sending a 404 before this is merged.

Remove Workflow Config from Previous Annotations and Subject Ducks

---

src/components/SocialSection.jsx
src/containers/Navigator.jsx
src/containers/SubjectViewer.jsx
src/lib/get-subject-location.js

Fixes #173 
When submitting Classifications - notably of extremely long documents - users will sometimes encounter "Could not submit Classification" errors.
The root issue is that, when a user is, e.g. viewing Page 5 of a 5-page document, then submits, and the next document is only 2 pages, we get an array-out-of-bounds error that chains into a null reference error that triggers the "Could not submit Classification" error. (The Classification is actually submitted, incidentally.)
This PR adds strict checks around the point of error - `getSubjectLocation()` - and adds a nigh paranoid amount of checks to prevent null objects from ruining anyone's day.
_An example of the error in action. The error occurs right after I initiate the Submit Classification action, while I'm looking at page 5. …

Fix 173 - Add safeties to getSubjectLocation() to prevent "Could not submit Classification" error

---

src/styles/components/classifier-page.styl
src/styles/components/project-header.styl

Sorry. Two small items I forgot to adjust with the design updates branch from earlier. These changes are based on the image below.

Adjust Margin and Font Size in Classifier

---

src/components/AnnotationsPane.jsx
src/components/PendingAnnotation.jsx
src/components/SelectedAnnotation.jsx
src/containers/SubjectViewer.jsx

This is a major PR that changes the way we create Annotations. We're moving from multi-point annotations (i.e. one 'dot' for each word and the end of the line of text) to "single line" annotations (i.e. one dot at the start of the line of text, one at the end)
(Becky, if you're reading this because I tagged you, the tl;dr for you is that you need to give this the Design OK after we've done the code changes. Everything else is just code jibba jabba.)
Generally, three things:
1. _Temporarily_ disable all Previous Annotations until the Caesar aggregation is updated.
- `ducks/previousAnnotations` will just be hacked so that it assumes no results whatsoever.
2. Annotations should end after only two dots.
- Also, in SelectedAnnotation, disable word count logic.
- OPTIONAL (recommended?): revise …

Convert to "Single Line" Annotations

---

src/config.js
src/ducks/previousAnnotations.js

This PR specifies the Reducer keys when requesting aggregated data ("Previous Annotations From Other Users") from Caesar. This follows @CKrawczyk's comments from PR #198 
- If these Reducer keys are not specified, Caesar will pull different types of aggregated data (including completeness and previous incarnations of the 'Previous Annotations' data) when a request is made.
- While strictly speaking not harmful to have the extra data, said extra data can be unnecessarily confusing when we're debugging our code and requires too much implicit understanding of how the Caesar Reducers are set up. Explicit specificity makes things much clearer in context.
- For staging, the Reducer key is `ext-17`, for production, the Reducer key is `ext`.
Ready for review, @wgranger . This looks good on …

Specify Caesar Reducer Keys

---

src/components/FilmstripViewer.jsx
src/components/ProjectHeader.jsx
src/components/SelectedAnnotation.jsx
src/containers/ClassifierContainer.jsx
src/styles/components/classifier-page.styl
src/styles/components/project-header.styl

Fixes #79 
This PR creates a function that determines where the annotation box boundaries will lay and adjusts the box is out of bounds.
CSS styling was changed from margin to padding because `offsetWidth` and `offsetHeight` don't take margins into account.

Keep Annotation Box Within Window Bounds

---

src/ducks/classifications.js
src/ducks/subject.js

This wound up being a simple fix. Aside from indenting some lines in `fetchSavedSubject`, the only addition I made was adding a dispatch to fetch previous annotations once the saved subject is retrieved. 
Fixes #205

Retrieve previousAnnotations When Saved Subject is Loaded

---

src/containers/ClassifierContainer.jsx
src/containers/SubjectViewer.jsx

A slight adjustment was needed for the GoogleAnalytics logger for novel-transcription. Originally, the log was made whenever a user clicked on "annotate" on the right hang toolbar. However, now a log will be made when the _first_ dot is made in a line transcription.
Mentioned in #188

Change when novel-transcription is Logged

---

src/components/Banner.jsx

Currently, our ASM website has a special banner message that says `"We’re currently implementing some changes to the project based on feedback from our volunteers. Stay tuned for our next round of beta testing!"` if a user is *not logged in as an admin*
This doesn't make any sense as we go into Beta 2, so I'll remove it for the time being.
I'll take responsibility for merging this.
Note that I'm only commenting out the banner as I anticipate we'll need it in the future with new messages.

Remove Banner

---

src/ducks/classifications.js

This PR fixes an issue with IE11, where - currently - if you attempt to submit a Classification (Finish -> pages fully done/not fully done -> Done), you'll receive an alert that says "ERROR: Could not submit Classification" DESPITE the fact that the Classification was submitted (as verified by console and network logs.)
The problem was that - for some mysterious reason - IE11 doesn't know how to handle `Split.classificationCreated(classification)` in `submitClassification()`, so a simply try-catch was placed around it.
Ready for review, @wgranger

IE11 fix: allow Classifications to be submitted

---

src/ducks/project.js

Fixes #200 
This PR resolves the issue of a tutorial button not appearing for new users. Apparently, when fetching the project preference for a user, the tutorial logic was skipped if the preference was returned undefined. Turns out, an issue was already open that would implement this logic, but it had not yet been fixed.
Also fixed in this PR, it turns out the project_preferences call was made before the project resource was retrieved, so the project id is here used from the config instead.
To test this, you might need to create a new user or find a user who has not yet interacted with this project.

Resolve Tutorial Button Bug

---

src/components/LoadingSpinner.jsx
src/components/SVGImage.jsx
src/components/SubjectLoading.jsx
src/containers/SubjectViewer.jsx
src/ducks/classifications.js
src/styles/components/subject-viewer.styl

This PR places an SVG loading spinner in place of the previous pulsating circle. 
As always, a couple additional lines were modified per the linter's suggestions.
Closes #137

Functioning SVG Subject Loading Spinner

---

src/components/AnnotationsPane.jsx

There was a bug introduced in #209. In this branch, a hover help box was introduced to all previous transcripts (including red lines) while also removing click functions. While this is expected for consensus (gray) lines, click actions should not have been removed for red lines.

Allow Selecting Previous Annotations

---

src/components/Banner.jsx

This is a basic text update for the Banner that tells users that the Second Beta is over, based on #223 
- All users will see this Banner; there's no special requirement (e.g. have to be logged in/admin/etc) to see it.
Note that we _won't_ lock out the Transcribe page (like with after the first Beta) since there's no harm with curious users providing extra Beta 2 Classifications, and we didn't change any Classifier functionality, like we did with Beta 1.
Minor update, I'm merging & deploying this.

Update Banner - Second Beta is Over, Long Live ASM

---

src/components/ProjectHeader.jsx
src/components/SocialSection.jsx

This is to be merged once we are finished with beta and ready for the full launch. This PR currently hides the incorrect project stats in lieu of a stats link on the navbar until we choose which variant (collaborative or individual) we want to stick with. 
A further description is in #220

Add Stats to Navbar and Hide Landing Page Stats

---

src/components/App.jsx
src/components/Banner.jsx
src/components/Home.jsx
src/config.js
src/containers/ClassifierContainer.jsx
src/ducks/login.js
src/ducks/subject.js
src/styles/components/top-banner.styl

This branch removes all mentions of beta in both the code and UI. The PR is currently RFC because there are a few items to discuss.
- Although I understand why `login.initialised` is present in the ducks, I'm not sure it is changing much in the frontend logic. 
- Although the top banner was initially marked `BETA_ONLY`, I think it makes sense to keep it in if we want to make an announcement in the future.
- It's possible we will need subject set selection once more subject sets are introduced. For now, the comments were changed to `INITIAL_LAUNCH_ONLY`

[RFC] Remove Beta Mentions

---

src/components/SelectedAnnotation.jsx

A small line change was made to better reflect what is going on with this event type when logged to Google Analytics.

Change Log Type for Previous Annotation

---

src/ducks/previousAnnotations.js
src/index.tpl.html

My initial testing of this branch, after the addition of `es6` to the polyfill, appears to solve the issue of logging `Split.classificationCreated()`, but my console access w/ my IE VM is a little spotty, so it's worth a further review before any merge.
Fixes #214

Allow IE to Log Seven-ten

---

src/store/index.js

This PR removes redux logging in the console from production. Solution was sourced from the redux-logger [docs](https://github.com/evgenyrodionov/redux-logger#log-only-in-development).

Remove Redux Logger from Production

---

src/components/Banner.jsx

The teal banner at the top of the website that says _"Thanks for participating in our beta review! We're making some changes based on your feedback, and will be launching the full project soon!"_ which doesn't make any more sense now that we're heading into a full launch.
This PR removes it.
I'm going to merge & deploy this.

Remove banner message for full launch

---

src/ducks/classifications.js
src/ducks/login.js
src/ducks/subject.js

Background: ASM users are encountering issues submitting Classifications and we don't know why. One clue is that a number of said users tried using the Save Progress feature, and we detected that there may be an issue with `retrieveClassification()` function
This PR:
- Adds more console logs (for both successes and failures) which will be picked up by Rollbar, which should help future debugging.
- Fixes `retrieveClassification()` so that it no longer uses the `Array.shift()` method, because that actually changes the value of the `classification` object... and the Panoptes `classification` object should _only_ have its values changed via the `classification.update()` method.
- Note: As far as I can determine, the values shift()ed in the `classification()` _don't need to be changed_ at …

More Error/Status logging and remove shift() from retrieveClassification()

---

src/ducks/classifications.js

DERP. The `catch()` clause doesn't have `classificationObject`, so it doesn't make sense for `console.error()` to report it.
@wgranger please take a look at this.

Removed classificationObject from catch()

---

src/ducks/classifications.js

This is a messaging issue. When a Classification is submitted and a 422 is received in response, it means the Classification is invalid (something must have gone horribly wrong with the code) and therefore _cannot_ be re-queued.
This PR ensures that the "we'll try again later" message _only_ appears when a failed Classification is re-queued. (i.e. anything but a 422)
Ready for review, @wgranger

Failed Classifications with 422 errors shouldn't pop an alert

---

src/components/AboutTheCollection.jsx
src/components/AlreadySeen.jsx
src/components/AnnotationReminder.jsx
src/components/Home.jsx
src/components/KeyboardShortcuts.jsx
src/components/SaveClip.jsx
src/components/SelectedAnnotation.jsx
src/components/ShowMetadata.jsx
src/components/SocialSection.jsx
src/components/Timeline.jsx
src/containers/ClassifierContainer.jsx
src/containers/Navigator.jsx
src/containers/SubjectViewer.jsx
src/ducks/subject.js
src/index.tpl.html
src/lib/timeline-events.js
src/styles/components/font-groups.styl
src/styles/components/home-page.styl

This PR covers several items:
- Tweaks content, including typos
- Adjusts some problems with the timeline (the long gray event covering up another event, having to double click to activate an event)
- Adds note on landing page about mobile devices and tablets
- Solves some linter errors as they appear
- Fixes some existence issues on several components that appeared via Rollbar
- Adds links to Subjects of Note on landing page
- Removes the `finally()` polyfill, which is no longer needed
Closes #239

Change Content and Minor Errors

---

src/components/AboutTheProject.jsx
src/styles/components/about-project.styl

This adds some content to the about the project page explaining to users what we plan to do with the transcribed text.

Add Content and URL to About Page

---

src/ducks/classifications.js

This PR changes the text the user sees when `submitClassification()` fails, to avoid confusion on what's happening and what the user should do.
Previously:
_"Your Transcription could not be submitted at this time. However, we've saved your work on this computer and it will automatically be resubmitted the next time you submit a Transcription. Please refresh the page to start working on a new letter."_
Now:
_"Your Transcription could not be submitted at this time. However, we've saved your work on this computer and it will automatically be resubmitted the next time you submit a Transcription. Please refresh the page to start working on a new letter."_
Text update, self-merging.

Update text for when Classifications fail to better reflect reality

---

src/components/SelectedAnnotation.jsx

There is a reference to the dropdown box in the transcription pane. This reference appears when the user is in _both_ "individual" and "collaborative" modes. It should only appear in "collaborative."

Change Transcription Instructions

---

package-lock.json
package.json
src/components/App.jsx
src/components/DialogOfContinuation.jsx
src/components/DialogOfFailure.jsx
src/ducks/classifications.js
src/ducks/emergency-save.js
src/ducks/previousAnnotations.js
src/ducks/subject.js

This PR aims to solve the issue where a user's login token may expire while the user is in the process of transcribing some work, and the Panoptes Client forgets to refresh the token.
- The Panoptes Client has been updated to 2.9.2, which now includes a `apiClient.beforeEveryRequest()` hook and an `oauth.checkBearerToken()` function.
- See zooniverse/panoptes-javascript-client#81 for details on how such unexpected timeouts might occur.
Jim provided some useful notes:
```
apiClient.beforeEveryRequest = function() {
return oauth.checkBearerToken()
.then(function (token) {
// still logged in. Probably don't need to do anything here
})
.catch(function (error) {
// Token couldn't be renewed. Message that they are about to be logged out
// or call oauth.signIn(url) to redirect to …
```

Update Panoptes Client, handle timeout sessions

---

src/lib/get-session-id.js

While adding the get-session-id.js file to Ancient Lives, I noticed in `#getSessionID()` that `ttl < Date.now()` never returned true.
https://github.com/zooniverse/anti-slavery-manuscripts/blob/6b3aee3c51cb26273b20664bb218a946581000d4/src/lib/get-session-id.js#L25-L26
The method is comparing a string representation of a Date object with a number representation of a Date object. This PR makes a small adjustment so that integer value representations are compared instead.

getSessionID() should compare integer representations of Date objects

---

src/ducks/subject.js

Currently, if a user clicks the favorite button, but no collection of favorite subjects exists, the application creates a collection but does not add the current subject to the collection.
This PR, based on the [FavoritesButton from PFE](https://github.com/zooniverse/Panoptes-Front-End/blob/c14f06f7aa93949e2a9afa307db96b9267d4a74b/app/collections/favorites-button.jsx), creates a new collection of Favorites and then adds the selected subject to that collection.

After creating a new collection for favorite subjects, add the selected subject

---

package-lock.json
package.json
webpack.production.config.js

Fixes a github security warning for the string dependency in older versions of markdownz.
Updates the webpack config because two of the markdown plugins are now written in ES6, so should be passed through babel.

Update markdownz to 7.6.3

---

package-lock.json
package.json

Ran `npm audit fix` after getting a security warning about this package still using an old version of superagent. We updated superagent in panoptes-javascript-client, so this project was a few minor versions behind with PJC. I didn't test this app at all, but the update went fine with PFE.

Updated packages after running npm audit fix

---

package-lock.json
package.json

This PR updates `panoptes-client` to v2.11.2, which is necessary for compatibility with one of Panoptes's upcoming updates. See https://github.com/zooniverse/panoptes-javascript-client/pull/103 for further details.
Mergin' & deployin'!

Update PJC to 2.11.2 for compatibility with new Panoptes updates

---

src/components/Banner.jsx
src/containers/ClassifierContainer.jsx
src/styles/components/top-banner.styl

This PR comes on the heels of #262 and makes two changes.
- Adjusts the button text from "solo" to ~~"collaborative"~~ "independent" for the workflow selection button to keep naming consistent. 
- Reintroduces the announcement banner to the top of ASM notifying users of the feedback form.

Update Button Text and Add Announcement Banner

---

src/components/SelectedAnnotation.jsx
src/ducks/annotations.js
src/ducks/previousAnnotations.js

Closes #270 
This solves the issue of users accidentally deleting their previous annotations. 
Previously, selected annotations were deleted by matching the `selectedAnnotationIndex` with the same index in the completed annotations array. This caused issues when the selected annotation was a previous annotation (red line) because the `selectedAnnotationIndex` would incorrectly be calculated in relation to other red lines instead of in relation to blue (user) lines.
Instead of using index numbers, a selected annotation is now deleted by matching it with the correct points of all user annotations. 
Some changes in this PR also attempt to get rid of linter errors.

Find Annotation to Delete By Points

---

src/components/SelectedAnnotation.jsx

There's a bug in the transcription interface where users are able to select "done" on a transcription pane when there is no text in the input box. This can lead to a confusing UI where users may think they are selecting and recording annotations that are actually empty. This was first  found in [this](https://www.zooniverse.org/projects/bostonpubliclibrary/anti-slavery-manuscripts/talk/1183/647976) talk post.

Disable Done Button With Empty Transcription

---

src/components/App.jsx

This PR fixes an issue where the Resume Progress popup doesn't show, even if the user has Saved Work In Progress (as shown in the browser cookies). Turns out the problem is that sometimes the Classifier page attempts to find a user's work in progress before realising if there's a user to begin with.
See #274 for more details.
Fixes #274 
In any case, this initialisation check is good practise for _all our projects_ as the whole _point_ of the `.initialised` parameter is to tell the app that it's ready to render (at least in terms of user login checks).
Note to self: check out projects to ensure that this is also in place.
@wgranger this is ready for review. If everything's OK, can you also please help deploy the fix? I need to head off shortly-ish.
Tagging @snblickhan so we can update our …

Fix missing "Resume Progress" popup - don't render app until login is initialised

---

src/components/SelectedAnnotation.jsx
src/containers/ClassifierContainer.jsx
src/ducks/splits.js

Do not merge until we get the green light from the BPL team that the field guide has been updated and new subjects added.
This PR removes workflow selection from the classifier. I _think_ all our bases are covered here; however, with all the code to check for variants, it would be good to have a sharp eye on this. In a nutshell, changes here:
- Set default variant to `collaborative`
- Remove workflow selection section
Most of the code referencing variants and independent mode has been left in should we choose to revert back to that variant at some point.

Remove Workflow Selection

---

package-lock.json

This PR reverts package-lock.json to a [version](https://github.com/zooniverse/anti-slavery-manuscripts/commit/87828ec9849b0aff915cfa165e3fd2ce9a13a3e7) where ZRC Tutorials still work.
Does this sound ridiculous? Of course it does! But there's some weird magical curse that breaks the Tutorial from the Zooniverse React Components (i.e. the Tutorials won't display), IF you installed fresh dependencies _after_ commit [87828ec](https://github.com/zooniverse/anti-slavery-manuscripts/commit/87828ec9849b0aff915cfa165e3fd2ce9a13a3e7)
So basically, if you do this...
`git checkout 87828ec ; rm -fr node_modules ; npm install ; npm start`
...everything works fine! If you go to the Classify and click on the "Tutorial" button, the tutorial appears!
However, if you do this...
`git checkout 034417e ; rm …

Fix ZRC Tutorial aka The Magical Curse of Package-Lock.JSON

---

src/components/AnnotationsPane.jsx
src/components/App.jsx
src/components/ClassificationPrompt.jsx
src/components/Home.jsx
src/components/SelectedAnnotation.jsx
src/containers/ClassifierContainer.jsx
src/containers/CollectionsContainer.jsx
src/ducks/classifications.js
src/ducks/emergency-save.js
src/ducks/field-guide.js
src/ducks/login.js
src/ducks/previousAnnotations.js
src/ducks/project.js
src/ducks/subject.js
src/ducks/tutorial.js
src/ducks/workflow.js

Closes #284 
Users are reporting errors of seeing annotations from different subjects. This PR attempts to solve those issues by making several changes:
**Main changes:**
- Fixes a bug where users can submit a blank classification using keyboard shortcuts (ctrl + enter). Try selecting a previous annotation, keep the box blank, and hit the shortcut.
- Ensure subject id fetched from Caesar matches the displayed subject id.
- Fix error seen in Rollbar where user tries to update a non-existent annotation (probably from incorrectly shown lines of a previous annotation).
- Adds catches to all promises.
**Other changes:**
- Fixes various linter issues, mainly line indents
The main error received from Rollbar recently is an `unhandled rejection was null or undefined!` error stemming from [this …

Improve Caesar Error Handling

---

package-lock.json
package.json

This manually updates ZRC. Running npm audit fix doesn't automatically update packages installed directly from github, fyi. I ran npm audit fix again as well.
The test runner appears to be broken, so I don't know if this will break anything.

Update ZRC and run npm audit fix

---

package-lock.json
package.json

Reverts zooniverse/anti-slavery-manuscripts#289
While testing the website on localhost looks fine, for some reason `https://www.antislaverymanuscripts.org/` refused to show anything on the page with the latest PR 3289 updates deployed.
- Blank page when viewing website on OSX+Chrome
- No error messages in the console.
- HTML, JS, and CSS files look like they exist.
I'm reverting #289 to figure out what's going on here that's specific to the production deployment. For the moment, `https://www.antislaverymanuscripts.org/` has been re-deployed with the reversions and looks fine.

Revert "Update ZRC and run npm audit fix"

---

package-lock.json
package.json

This is a maintenance update
- PJC has been upgraded to 2.12.3
- `npm run fix` has been executed to clean up a bunch of dependency warnings
This PR follows the batch security update (#292 #294 #295 #297 #298) and will be deployed with all those security fixes in tow. 
Note: we are _still_ seeing the `this.updater.enqueueCallback is not a function` that's caused by some of the ZRC components using a different version of React than what we're currently using. This is... annoying but not breaking, as far as I can tell.
@wgranger if you have time to confirm this, it'd be much appreciated.

Update Panoptes JavaScript Client and several dependencies

---

package-lock.json
package.json

This PR updates the Zooniverse React Components package to the latest version, which uses React 16, matching the rest of this project. As a result, this removes the `this.updater.enqueueCallback is not a function` error that's popping up in the consoles.
Merging, go.

Update ZRC to remove `this.updater.enqueueCallback is not a function` error

---

package.json

This PR creates a staging script so we can get a staging version deployed. This will make it easier for other users to log in and submit staging classifications through the CFE.
**Use case:**
We need to test out the ALICE pipeline, but we'd like to try it with a fresh subject set. I've created a subject set on ASM staging for this purpose, but I'd like multiple people to submit classifications. Rather than get multiple non-devs set up with the local app, etc. etc. I think it'd be easier to get a staging site deployed, finally.

Create Staging Script

---

src/index.tpl.html

I noticed recently when trying to share ASM on a social media platform that the preview looked pretty bad. I believe these changes should take care that. There's some documentation [here](https://developers.facebook.com/docs/sharing/webmasters/) and I used a wordpress image from the Daily Zoo as the image.

Add Ogg Tags

---

src/index.tpl.html

og:title should read "Anti-Slavery Manuscripts," instead of "Anti-Slavery Manuscript"

Fix Typo in og Title

---

package-lock.json
package.json

Update Zooniverse-React-Components to v0.9.1, which includes security vulnerability patches, but no changes.
On other repos I've been using this as an excuse to also run an `npm audit fix`, let me know if would also like me to open that PR, or I'd be happy to review that PR, and get both in for a deploy.

Update Zooniverse-React-Components to v0.9.1

---

src/components/KeyboardShortcuts.jsx
src/containers/ClassifierContainer.jsx

Forgot to remove the "annotate" quick-key when merging #316. This remove the quick key functionality as well as the mention of it in the Shortcuts modal.

Remove Annotate Key Shortcut

---

webpack.config.js
webpack.production.config.js

Removes public path configuration from the webpack output because folders are fake on azure.

Remove the public path configuration to work on azure

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
package.json

Follows #350
This PR fixes the GitHub Action deployment. Currently, the deployment is failing due to an older version of `npm` (tied with node 14) trying to install packages from a package-lock.json created by newer versions of `npm`
- Now we're using `node 16`, which should come with the newer versions of npm
- `npm install` has also been replaced with `npm ci`

Upgrade Node to 16, fix deployment

---

.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

As noted in other repos using Node v16.15 or higher in builds (latest build issues in this repo are with Node v16.16) - builds with Node > 16.15 fail with unmatched peer dependency errors - new Node versions are more strict about nested dependencies.
This PR sets node to v16.14 to fix the builds.
I think the long term solution might be to utilize the `--legacy-peer-deps` flag. I'll create an issue for that, to document and discuss.

Set Node to 16.14 to fix build issues

---

package.json

This PR fixes an issue where the build process incorrectly builds targeting the staging/dev environment, instead of the production environment.

Build: use production Node env
