- src/components/LoginButton.jsx
- src/styles/components/app-header.styl
- src/styles/components/logout-button.styl
* Minor fix to the look of the login button.
* From:
* To:
> Fix Login button styling

- package.json
> Add React Components to package.json

- src/components/App.jsx
- src/components/Header.jsx
- src/components/Home.jsx
- src/components/TmpSvgIcon.jsx
- src/containers/ClassifierContainer.jsx
- src/index.jsx
- src/index.tpl.html
- src/styles/components/app-content.styl
- src/styles/components/app-header.styl
- src/styles/components/app-layout.styl
- src/styles/components/classifier-page.styl
- src/styles/components/temp-placeholders.styl
- src/styles/global/app-theme.styl
- src/styles/global/root.styl
* This PR updates the visual look (colours, fonts, layout, etc) to match the latest (v3) design guide.
* This is mostly a design placeholder; functionality is not being built yet.
* We are still missing a shared Zooniverse header, but this should be coming from the Zooniverse-React-Components library.
https://indd.adobe.com/view/e2b8cf36-eb64-4e7b-8cf0-c923214d2e67
> Design v3 style update

- README.md
- package.json
- src/components/Home.jsx
- src/components/SVGImage.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/SubjectViewer.jsx
- src/ducks/subject.js
- src/index.tpl.html
- src/styles/components/app-header.styl
Ok, this was pretty straightforward once I got reacquainted with Redux. However, the main question here is, where do we want the call made to Redux to fetch the next subject in a queue.
I also removed all references to Liberating the Liberator, aside from a url in one place as we are still not positive of that address.
> Fetch Testing Images

- src/components/Popup.jsx
- src/containers/ClassifierContainer.jsx
- src/styles/components/popup.styl
* This PR is for @wgranger to review; the important thing is sharing some functional popup modal code, which can then be updated as necessary.
* In this PR, we have an example of how we can create a simple "message popup" for the project.
* The `<Popup>` component is a simple container and can be placed in any container/component you want.
* Clicking on either the 'close' cutton or on the black background will close the popup.
* **Of note,** the show/hide logic of the Popup container is actually handled on the parent container/component.
* The style is up for debate and has plenty of room for improvement. E.g. make it fit content instead of trying to fit the screen.
* Possible bug?: the popup _doesn't steal events_ when active, so you can technically still mouse-scroll the background …
> [For Review] Added a sample Popup

- src/components/Popup.jsx
- src/components/ShowMetadata.jsx
- src/containers/ClassifierContainer.jsx
- src/styles/components/classifier-page.styl
- src/styles/components/popup.styl
- src/styles/components/show-metadata.styl
Closes #35 
This PR adds a simple metadata popup to the classifier. The design is based on the metadata popup in PFE. Hover states are also added to the CSS of toolbar buttons.
> Functioning Metadata Popup

- package.json
- src/components/CollectionsManager.jsx
- src/components/Popup.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/CollectionsContainer.jsx
- src/ducks/collections.js
- src/ducks/reducer.js
- src/styles/components/collections-manager.styl
- src/styles/components/popup.styl
This PR creates the collections manager popup. The form is quite similar to what we have on PFE and also uses react-select. Note: some `!important` styling was necessary to escape default styling set by the component.
> Collections Popup

- src/containers/CollectionsContainer.jsx
This takes care the issue of the collection popup closing before displaying errors with collection adds.
> Fix Errors with addToCollection

- src/components/AboutTheCollection.jsx
- src/components/MobileTimeline.jsx
- src/components/Text.jsx
- src/components/Timeline.jsx
- src/lib/timeline-events.js
- src/styles/components/about-collection.styl
- src/styles/components/timeline.styl
This is a relatively large PR, but there was some SVG magic needed to get animations to work properly. It appears to be working in all browsers aside from IE (where a bit more work is necessary). If hesitant to merge with how the timeline functions with IE, this can become a WIP. Otherwise, an issue can be opened once merged. 
This was my first foray into SVG animations, so there might be some code that can be cleaned up. The Text component was created to allow dynamic, multi-line SVG text objects with `tspan`.
> About Timeline

- package.json
- src/components/App.jsx
- src/components/Dialog.jsx
- src/components/Popup.jsx
- src/components/ShowMetadata.jsx
- src/containers/ClassifierContainer.jsx
- src/ducks/dialog.js
- src/ducks/reducer.js
- src/styles/components/popup.styl
- src/styles/components/show-metadata.styl
Some styling changes were made to the metadata popup. Also, the popup itself was changed from a modal into a popup that could be moved around. This was also done by moving the popup into redux and making it available on the root page so absolute positioning would place the popup consistently.
> Restyle Metadata Popup and Create Dialog

- src/components/AnnotationsPane.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/SubjectViewer.jsx
- src/ducks/subject-viewer.js
The ability to toggle previous marks was added to the classifier and works through Redux.
> Toggle Previous Marks Functionality

- src/components/SocialSection.jsx
- src/index.tpl.html
- src/lib/get-subject-location.js
- src/styles/components/about-collection.styl
- src/styles/components/classifier-page.styl
- src/styles/components/home-page.styl
- src/styles/components/temp-placeholders.styl
IE has some knows issues with Flexbox, so many of the changes here were in response to those issues. Also, IE doesn't support `.include()` when fetching an image src, so `.indexOf()` was used in place.
> Fix IE Issues

- src/components/Home.jsx
- src/lib/letter-groups.js
- src/styles/components/classifier-page.styl
- src/styles/components/home-page.styl
The homepage css was all out of whack with respect to multiple browsers, mobile, etc. Note: an audit of the site will prob have to be made eventually in IE.
This also adds the placeholder subject sets of letter groups.
> Fix CSS on Homepage for Responsive Viewing

- src/components/AboutTheCollection.jsx
- src/components/AboutTheProject.jsx
- src/components/App.jsx
- src/components/ProjectHeader.jsx
- src/index.jsx
- src/lib/project-members.js
- src/styles/components/about-project.styl
- src/styles/components/project-header.styl
An additional about page was created for the project. The design can be found [here](https://projects.invisionapp.com/share/A3CXG9IK7#/screens/254595512). 
Currently, placeholders are being used for several images on the page. A couple tweaks were also made to the project header menu.
> About the Project Page

- package.json
- src/components/App.jsx
- src/containers/ClassifierContainer.jsx
- src/ducks/reducer.js
- src/ducks/splits.js
- src/index.jsx
- src/lib/location-match.js
- src/lib/split-config.js
This PR sets up retrieval of seven-ten split data in preparation for visibility splits. Some more visual additions need to be merged into this repo before visibility components can be added.
> Prepare Splits for Visibility Tests

- src/components/AboutTheCollection.jsx
- src/components/AboutTheProject.jsx
- src/components/ProjectHeader.jsx
- src/components/SocialSection.jsx
- src/lib/project-locations.js
This quick PR adds the correct project ids and slugs based on the node environment. Social media links are also added for BPL.
> Add Project Links

- package.json
- src/components/Header.jsx
- src/containers/AuthContainer.jsx
- src/ducks/login.js
- src/styles/components/app-header.styl
This PR uses the shared `Header` component from Zooniverse-React-Components. While an earlier commit of this branch contained some functionality for a modal popup with Google sign-in, some discussion is still needed to flesh out the login procedures for the app. The branch should be stable and working.
> Add header

- src/components/Home.jsx
- src/components/SocialSection.jsx
- src/lib/get-subject-location.js
- src/styles/components/home-page.styl
This PR adds functionality to retrieve recent subjects from a project's talk board.
> Get Recent Subjects on Home Page

- src/components/SocialSection.jsx
Just a check that `subjectsOfNote` isn't `null`.
> Add Existential Check

- src/components/AnnotationsPane.jsx
- src/components/App.jsx
- src/containers/AuthContainer.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/SubjectViewer.jsx
- src/ducks/classifications.js
- src/ducks/previousAnnotations.js
- src/ducks/splits.js
- src/styles/components/classifier-page.styl
This should be set up properly, but I am going to double check we are submitting seven-ten classifications correctly. I have confirmed (using two test users) that previous annotations will only appear if a user is in the collaborative variant.
Edit: Switching this to WIP while I confirm seven-ten is queried correctly.
Closes #70
> Seven Ten Views

- src/components/AnnotationsPane.jsx
- src/config.js
- src/ducks/previousAnnotations.js
This PR was done pretty quickly based on some conversation about reaching a line consensus. In this branch, a line will have reached consensus if the consensus score is three or above. When that happens, the onClick for the line disappears and the line appears grey. I believe this is the last item needed for issue #64.
Closes #64
> Color Grey Consensus Line

- src/containers/ClassifierContainer.jsx
Going to knock this out quickly so it doesn't fly under the radar.
> Add Done and Talk Functionality

- src/components/SelectedAnnotation.jsx
- src/styles/components/popup.styl
- src/styles/components/selected-annotation.styl
A few small design changes were made to the annotations pane as well as the addition of the "underline" text modifier (whose functionality will need to be added soon).
> Redesign Annotations Pane

- src/components/App.jsx
- src/components/LoadingSpinner.jsx
- src/styles/components/loading.styl
Closes #128 
This PR designs a loading spinner more along with the style of the website.
> Style Loading Spinner

- package.json
- src/components/App.jsx
- src/components/ProjectHeader.jsx
- src/components/SelectedAnnotation.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/SubjectViewer.jsx
- src/ducks/splits.js
- src/index.tpl.html
- src/lib/GoogleLogger.js
- src/lib/ga-log-adapter.js
- src/lib/geordi-log-adapter.js
- src/styles/components/project-header.styl
Much of the work on this branch is based on work done with a [current PFE PR](https://github.com/zooniverse/Panoptes-Front-End/pull/4130). 
Some GA tracking items are [still pending](https://docs.google.com/document/d/1BkwASryrJmIqF84yc0Ce6fh9xJHTqG154SNTlyQkt7o/edit), but they are dependent on some other additions made to the app. Additionally, some additions will need to be made on PFE.
General test info can be found [here](https://docs.google.com/document/d/14_dJVVIb9nifF8REQTmDaWjFqD-d0wc6jhlGflt9_Mc/edit).
You should be able to confirm click tracking is sent to Google Analytics and Geordi by keeping an eye on the Network tab while navigating the site.
> Add Google Analytics and Geordi Logging

- src/components/SocialSection.jsx
- src/ducks/login.js
- src/ducks/project.js
- src/index.tpl.html
- src/styles/components/font-groups.styl
- src/styles/components/project-header.styl
- src/styles/global/app-theme.styl
This PR simply closes a few issues that were present. The two main issues are the use of fonts and fixing the tutorial/preferences bug.
Closes #127 
Closes #132
> Fix outstanding issues

- src/components/SelectedAnnotation.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/SubjectViewer.jsx
- src/ducks/annotations.js
- src/styles/components/home-page.styl
- src/styles/components/project-header.styl
- src/styles/components/subject-viewer.styl
This PR fixes outstanding UI/UX issues introduced after the initial internal review.
See #142
> Fix UX Issues After Internal Review

- src/components/SelectedAnnotation.jsx
- src/ducks/subject.js
Two issues are fixed with this PR:
1) Text modifiers account for [unclear] being a word that can wrap correctly with other text modifiers.
2) On grabbing a new subject, the frame reverts back to 0.
> Fix Logic Issues From Internal Review

- src/components/ShowMetadata.jsx
> Hide Secret Metadata Columns

- src/components/App.jsx
- src/components/Header.jsx
- src/config.js
- src/ducks/login.js
- src/ducks/splits.js
- src/ducks/workflow.js
Closes #148 
This PR successfully calls a collaborative workflow based on which split group a user is placed into. However, there is still a lingering issue of resolving the first task which can be seen in the issue above.
**Note**: This has been tagged WIP until the task number issue above has been solved.
> Wait for Splits to Retrieve Workflow

- src/components/App.jsx
- src/components/Banner.jsx
- src/index.tpl.html
- src/styles/components/banner.styl
This PR adds a banner component to the app reminding users to login during beta launch.
> Create Announcement Banner for Beta

- src/ducks/annotations.js
Fixes #167 
This fix was made via the suggestion on the issue.
> Only Open Dialog without Selected Annotation

- src/components/App.jsx
- src/components/ClassificationPrompt.jsx
- src/components/Dialog.jsx
- src/components/Home.jsx
- src/components/SaveSuccess.jsx
- src/containers/ClassifierContainer.jsx
- src/ducks/annotations.js
- src/ducks/classifications.js
- src/ducks/dialog.js
- src/ducks/subject.js
- src/styles/components/about-collection.styl
- src/styles/components/about-project.styl
- src/styles/components/app-layout.styl
- src/styles/components/classification-prompt.styl
- src/styles/components/classifier-page.styl
- src/styles/components/submit-classification-form.styl
This is the last major bit of code being opened before beta. There is a lot going on here, and I changed the approach to save classifications on Panoptes instead of dumping them onto `localStorage`. I'm open to any suggestions and can explain any bit of code that might be perplexing. 
Note: This is not mandatory for beta but would be nice to introduce in time for the full launch.
> Save Classifications for Later

- src/components/App.jsx
- src/components/Banner.jsx
- src/components/ProjectHeader.jsx
- src/containers/ClassifierContainer.jsx
- src/styles/components/project-header.styl
This is a simple PR to hide the classifier to non-admin while we are in a beta pause. The banner message was also changed. There are many ways to implement what is done in this PR, this seemed the best method I thought of.
> Hide classifier from non-admins

- src/components/KeyboardShortcuts.jsx
- src/components/ProjectHeader.jsx
- src/components/SelectedAnnotation.jsx
- src/containers/ClassifierContainer.jsx
- src/styles/components/keyboard-shortcuts.styl
- src/styles/components/project-header.styl
This PR makes some changes as suggested in the comments of #188.
The branch also allows non-users to make classifications.
Closes #203
> Pre-Beta Two Feedback Updates

- src/components/AnnotationsPane.jsx
- src/components/CribSheet.jsx
- src/components/Crop.jsx
- src/components/Dialog.jsx
- src/components/FieldGuide.jsx
- src/components/SaveClip.jsx
- src/components/ShowMetadata.jsx
- src/containers/ClassifierContainer.jsx
- src/containers/SubjectViewer.jsx
- src/ducks/subject-viewer.js
- src/styles/components/classifier-page.styl
- src/styles/components/crib-sheet.styl
- src/styles/components/field-guide.styl
This component likely still needs some work, so it will be WIP for now. I still need to dummy check the code, but I'm putting it up now mainly to skim through and also test out. At this point, I mainly want someone to test it out to determine if there is something obviously out of place. Some other questions to consider.
- Should we add a keyboard feature to escape from cropping mode? Ex: Pressing `esc` goes back to navigation mode on the subject viewer.
Closes #9 
TODO: 
- Make the `SaveClip` component's dialog modal more narrow.
> Crib Sheet

- src/components/App.jsx
- src/components/Banner.jsx
- src/ducks/banner.js
- src/ducks/reducer.js
- src/styles/components/beta-only.styl
This PR adds a banner item to the redux store, allowing the banner to be removed on a "close" click. The message is also changed due to the recent beta two launch.
> Update Banner and Allow Removal

- src/components/AboutTheCollection.jsx
- src/components/AnnotationsPane.jsx
- src/components/CribSheet.jsx
- src/components/FieldGuide.jsx
- src/components/Thumbnail.jsx
- src/containers/ClassifierContainer.jsx
- src/ducks/splits.js
- src/styles/components/about-collection.styl
- src/styles/components/crib-sheet.styl
- src/styles/components/field-guide.styl
- src/styles/components/project-header.styl
Fixes #98 
This takes care of most of the issues included in #210. Each issue is fixed in a commit, so it might be helpful to review this PR by commit if that makes it easier to isolate and review each issue.
> Fix Issues from Beta Two Notes

- src/components/AboutTheCollection.jsx
- src/components/AboutTheProject.jsx
- src/components/AnnotationReminder.jsx
- src/lib/project-members.js
This PR fixes minor typos, punctuation, and content.
> Fix Minor Typos

- src/components/ProjectHeader.jsx
This PR adds "Blog" to the project header, as well as click tracking for Google Analytics.
> Add Blog to Project Header

- src/components/SubmitClassificationForm.jsx
Instead of directing to the talk board, Done & Talk now redirects to a specific subject on the board. 
Closes #236
> Redirect Done and Talk to Subject Post

- src/ducks/classifications.js
This PR introduces a classification queue similar to the one used in PFE. It would be good to have a second set of eyes on this functionality. There's a good bit going on in the classifier, and although the code _appears_ sound, it would be nice to get another set of eyes on it.
Also, I was unable to recreate the original bug this solved to fix. I attempted to recreate the bug by beginning a classification and attempting to submit said classification after an hour, so I'm not positive this PR will fix the issue we were experiencing.
Closes #173
> Introduce Classification Queue

- src/ducks/classifications.js
Slight change in the wording for the failure alert(). Minor content update, so I'll merge this.
> Minor text update on Submit Classification failure

- src/index.tpl.html
I have a feeling we might need this finally polyfill, and we may even want to consider another solution since the [Polyfill service](https://polyfill.io/v2/docs/features/) doesn't support Edge 7-11
> Add Finally Polyfill

- src/ducks/classifications.js
Some browsers, for some unknown reason, can't properly handle `Promise.prototype.finally()`. This PR adds a workaround where there's still a way to run a "account for Classification.save() succeeding or failing" function after a `Classification.save()`.
This error was reported in two ways:
- Users comment that after they successfully succeeded in sending a Classification, they couldn't get the next Subject. (This is consistent with .finally() not running)
- There were specific `.finally()` errors reported by Rollbar, right before it died. Skynet rest its digital soul.
@wgranger this is ready for a review and, if it's OK, a deploy.
> Replace Promise.prototype.finally()

- package.json
Just a quick PR to update the client
> update panoptes client

- src/components/DialogOfContinuation.jsx
- src/ducks/classifications.js
- src/ducks/emergency-save.js
- src/ducks/subject.js
This is an optional PR - it changes PR #251 so that the Emergency Save system cares whether a user is logged in or not.
Optional - do not merge into 251 until we can confirm this is the kind of app behaviour that we want; but if we do go for it, please remember to merge this before 251 is.
Tagging @wgranger
> Optional for PR 251 - Emergency Save with login checks

- src/components/App.jsx
- src/components/DialogOfFailure.jsx
This PR updates the message shown when the Emergency Save triggers, and removes some debug stuff that was left over from #251 
Minor updates, tests OK on localhost, merging & deploying.
> Update Emergency Save message, remove debug variables

- src/ducks/previousAnnotations.js
Dots were not appearing in collaborative mode. This fix should take care of the problem by using the recent changes to Caesar.
> Use subject_reductions

- src/components/AboutTheProject.jsx
- src/lib/project-members.js
Fixes #260 . This PR updates some content:
- Marilyn Morgan has been removed from the project team section (in the "About the Project" page).
- A typo in the "About the Project" page has been fixed.
Merging and deploying.
> Fix Issue 260 - minor content updates

- package-lock.json
- src/config.js
- src/ducks/previousAnnotations.js
- src/ducks/subject-viewer.js
This PR makes it easier for lines of text to be considered "retired", thus helping Subjects get retired.
As @CKrawczyk pointed out, the front end was checking that the consensus score exceeded a certain amount, but did not actually check if a line was already viewed a certain number of lines (to indicate that this is probably a line that's too difficult to get a consensus on, so should be retired anyway).
Closes #276 
Ready for review
> Make easier to retire

- src/containers/ClassifierContainer.jsx
- src/styles/components/app-general.styl
- src/styles/components/classifier-page.styl
This PR disables the collaborative option from the workflow selection window. This will be put in place temporarily until new subjects are uploaded.
> Disable Collaborative Option

- src/components/Banner.jsx
- src/containers/ClassifierContainer.jsx
Some quick work to pause the independent workflow in anticipation of introducing new subjects to collaborative mode later this week. 
First half of #279 
**Note:** Site should be redeployed once this is merged.
> Pause Independent Workflow

- package-lock.json
- package.json
- webpack.production.config.js
The intent of this PR is to re-do #289, except this time make it work when deployed to `https://www.antislaverymanuscripts.org/`. ⚠️ So far, I have not been successful. 😢 
Changes in this PR:
- Updated Zooniverse dependencies, as per #289 
- Ran `npm run audit`, as per #289 
- Removed the pointless `npm run test` and `npm run test-travis` scripts, which weren't really doing anything.
- Project now requires the use of Node v10
Unfortunately, I'm hitting the same snags that forced me to revert with #290 
- the ASM website looks fine on localhost, with `npm start` on OSX+Chrome
- However, when I run `npm run deploy-production`, the live website simply stops working. Blank page, no error messages in the console.
- ❓🤷‍♂❓ 
Observations:
- When I run `npm run deploy` I see only two files being …
> [DO NOT MERGE] Update ZRC and run `npm audit fix` - Mk2

- src/components/Banner.jsx
- src/containers/ClassifierContainer.jsx
- src/styles/components/app-general.styl
- src/styles/components/classifier-page.styl
- src/styles/components/top-banner.styl
ASM is (almost) done! This should merge once we are 100% finished with the subject set. 
**Note:** We need to change the "date" placeholder on the banner to be the day that we reach 100%.
**Changes**:
- Use existing banner to make finished announcement, but remove the close button to ensure the banner is always up.
- Disable the "annotate" button to keep users from making new transcriptions (had to make a few CSS changes here)
- Disable the "Submit" button so users are unable to submit new classifications.
> Finished banner

- .github/workflows/main.yml
Adds a github action to deploy this site to Azure. Uses credentials located on the zooniverse organization to login to azure and the `az` CLI utility to copy to the correct spot in `zooniversestatic/$web`.
> Add deploy github action

- .github/workflows/main.yml
Ope, got a different secret name there.
> Update name of secret

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Describe your changes:
- refactors GitHub Actions workflows to use shared zooniverse workflows - https://github.com/zooniverse/ci-cd/tree/main/.github/workflows
> Refactor workflows for Zooniverse shared ci/cd workflows

- .github/workflows/build_branch.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
- package-lock.json
- package.json
- update `package.json`.
- update GitHub workflows.
> Build with Node 18 (lts/hydrogen)
